project:
  type: website

website:
  title: "Carolinas Mowing Equipment"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: products.qmd
        text: Products
      - href: contact.qmd
        text: Contact
     

format:
  html:
    theme: cosmo
    toc: true

publish:
  gh-pages: true
